In [12]:
import torch
window_size = (7,7)

In [13]:
# get pair-wise relative position index for each token inside the window
coords_h = torch.arange(window_size[0])
coords_w = torch.arange(window_size[1])
print(coords_h)
print(coords_w)

tensor([0, 1, 2, 3, 4, 5, 6])
tensor([0, 1, 2, 3, 4, 5, 6])


In [14]:
coords = torch.meshgrid([coords_h, coords_w])
# print(coords.shape)
print(coords)
coords = torch.stack(coords)
# coords = torch.stack(torch.meshgrid([coords_h, coords_w], indexing="ij"))  # [2, Mh, Mw]
print(coords.shape)
print(coords)

(tensor([[0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6, 6]]), tensor([[0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6]]))
torch.Size([2, 7, 7])
tensor([[[0, 0, 0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3, 3],
         [4, 4, 4, 4, 4, 4, 4],
         [5, 5, 5, 5, 5, 5, 5],
         [6, 6, 6, 6, 6, 6, 6]],

        [[0, 1, 2, 3, 4, 5, 6],
         [0, 1, 2, 3, 4, 5, 6],
         [0, 1, 2, 3, 4, 5, 6],
         [0, 1, 2, 3, 4, 5, 6],
         [0, 1, 2, 3, 4, 5, 6],
         [0, 1, 2, 3, 4, 5, 6],
         [0, 1, 2, 3, 4, 5, 6]]])


In [15]:
coords_flatten = torch.flatten(coords, 1)  # [2, Mh*Mw]
print(coords_flatten.shape)
print(coords_flatten)

torch.Size([2, 49])
tensor([[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3,
         3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
         6],
        [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
         3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5,
         6]])


In [16]:
print(coords_flatten[:, :, None])
print(coords_flatten[:, None, :])

tensor([[[0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [2],
         [2],
         [2],
         [2],
         [2],
         [2],
         [2],
         [3],
         [3],
         [3],
         [3],
         [3],
         [3],
         [3],
         [4],
         [4],
         [4],
         [4],
         [4],
         [4],
         [4],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [6],
         [6],
         [6],
         [6],
         [6],
         [6],
         [6]],

        [[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [0],
    

In [17]:
# [2, Mh*Mw, 1] - [2, 1, Mh*Mw]
relative_coords = coords_flatten[:, :, None] - coords_flatten[:, None, :]  # [2, Mh*Mw, Mh*Mw]
print(relative_coords.shape)
print(relative_coords)

torch.Size([2, 49, 49])
tensor([[[ 0,  0,  0,  ..., -6, -6, -6],
         [ 0,  0,  0,  ..., -6, -6, -6],
         [ 0,  0,  0,  ..., -6, -6, -6],
         ...,
         [ 6,  6,  6,  ...,  0,  0,  0],
         [ 6,  6,  6,  ...,  0,  0,  0],
         [ 6,  6,  6,  ...,  0,  0,  0]],

        [[ 0, -1, -2,  ..., -4, -5, -6],
         [ 1,  0, -1,  ..., -3, -4, -5],
         [ 2,  1,  0,  ..., -2, -3, -4],
         ...,
         [ 4,  3,  2,  ...,  0, -1, -2],
         [ 5,  4,  3,  ...,  1,  0, -1],
         [ 6,  5,  4,  ...,  2,  1,  0]]])


In [18]:
relative_coords = relative_coords.permute(1, 2, 0).contiguous()  # [Mh*Mw, Mh*Mw, 2]
print(relative_coords.shape)
print(relative_coords)

torch.Size([49, 49, 2])
tensor([[[ 0,  0],
         [ 0, -1],
         [ 0, -2],
         ...,
         [-6, -4],
         [-6, -5],
         [-6, -6]],

        [[ 0,  1],
         [ 0,  0],
         [ 0, -1],
         ...,
         [-6, -3],
         [-6, -4],
         [-6, -5]],

        [[ 0,  2],
         [ 0,  1],
         [ 0,  0],
         ...,
         [-6, -2],
         [-6, -3],
         [-6, -4]],

        ...,

        [[ 6,  4],
         [ 6,  3],
         [ 6,  2],
         ...,
         [ 0,  0],
         [ 0, -1],
         [ 0, -2]],

        [[ 6,  5],
         [ 6,  4],
         [ 6,  3],
         ...,
         [ 0,  1],
         [ 0,  0],
         [ 0, -1]],

        [[ 6,  6],
         [ 6,  5],
         [ 6,  4],
         ...,
         [ 0,  2],
         [ 0,  1],
         [ 0,  0]]])


In [ ]:
relative_coords[:, :, 0] += window_size[0] - 1  # shift to start from 0
print(relative_coords.shape)
print(relative_coords)
relative_coords[:, :, 1] += window_size[1] - 1
print(relative_coords.shape)
print(relative_coords)
relative_coords[:, :, 0] *= 2 * window_size[1] - 1
print(relative_coords.shape)
print(relative_coords)


In [ ]:
relative_position_index = relative_coords.sum(-1)  # [Mh*Mw, Mh*Mw]
print(relative_position_index.shape)
print(relative_position_index)