In [1]:
import torch

# 梯度裁剪

In [6]:
# torch.clamp(input, min, max, out=None) → Tensor：将输入input张量每个元素的夹紧到区间 [min,max]，并返回结果到一个新张量。
a = torch.rand(2,2)
print(a)
a = a*10
print(a)
a = torch.rand(2,2)*10
print(a)

tensor([[0.1037, 0.3527],
        [0.8745, 0.7546]])
tensor([[1.0374, 3.5275],
        [8.7450, 7.5461]])
tensor([[2.3869, 6.0793],
        [1.6707, 8.2301]])


In [9]:
help(torch.clamp)
b = torch.clamp(a,2,7)
print(b)

Help on built-in function clamp:

clamp(...)
    clamp(input, min, max, *, out=None) -> Tensor
    
    Clamp all elements in :attr:`input` into the range `[` :attr:`min`, :attr:`max` `]`.
    Let min_value and max_value be :attr:`min` and :attr:`max`, respectively, this returns:
    
    .. math::
        y_i = \min(\max(x_i, \text{min\_value}), \text{max\_value})
    
    
    Args:
        input (Tensor): the input tensor.
        min (Number): lower-bound of the range to be clamped to
        max (Number): upper-bound of the range to be clamped to
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> a = torch.randn(4)
        >>> a
        tensor([-1.7120,  0.1734, -0.0478, -0.0922])
        >>> torch.clamp(a, min=-0.5, max=0.5)
        tensor([-0.5000,  0.1734, -0.0478, -0.0922])
    
    .. function:: clamp(input, *, min, out=None) -> Tensor
    
    Clamps all elements in :attr:`input` to be larger or equal :attr:`min`.
  

# 索引与数据筛选

   -  torch.where(codition,x,y):按照条件从x和y中选出满足条件的元素组成新的tensor，输入参数condition：条件限制，如果满足条件，则选择a，否则选择b作为输出
   -  torch.gather(input,dim,index,out=None):在指定维度上按照索引赋值输出tensor
   -  torch.index_select(input,dim,index,out=None):按照指定索引赋值输出tensor
   -  torch.masked_select(input,mask,out=None):按照mask输出tensor，输出为向量
   -  torch.take(input,indices):将输入看成1D-tensor，按照索引得到输出tensor
   -  torch.nonzero(input,out=None):输出非0元素的坐标

In [12]:
# torch.where(codition,x,y)
b = torch.rand(4,4)
c = torch.rand(4,4)
print(b)
print(c)
out = torch.where(b>0.5,b,c)
print(out)

tensor([[0.2675, 0.5273, 0.1901, 0.9465],
        [0.3886, 0.3042, 0.0509, 0.7136],
        [0.3067, 0.8536, 0.4764, 0.8760],
        [0.9923, 0.3294, 0.3638, 0.8732]])
tensor([[0.5966, 0.9615, 0.0232, 0.8825],
        [0.9075, 0.6064, 0.3109, 0.2927],
        [0.1184, 0.9410, 0.7856, 0.1840],
        [0.4286, 0.0283, 0.7988, 0.5401]])
tensor([[0.5966, 0.5273, 0.0232, 0.9465],
        [0.9075, 0.6064, 0.3109, 0.7136],
        [0.1184, 0.8536, 0.7856, 0.8760],
        [0.9923, 0.0283, 0.7988, 0.8732]])


In [17]:
# torch.gather(input,dim,index,out=None)
e = torch.linspace(1,16,16)
print(e)
e = e.view(4,4)
print(e)
out = torch.gather(e,dim=0,index=torch.tensor([[0,1,1,1],[0,1,2,2],[0,1,3,3]]))
print(out)
print(out.shape)
#dim=0, out[i, j, k] = input[index[i, j, k], j, k]
#dim=1, out[i, j, k] = input[i, index[i, j, k], k]
#dim=2, out[i, j, k] = input[i, j, index[i, j, k]]
out = torch.gather(e,dim=1,index=torch.tensor([[0,1,1,1],[0,1,2,2],[0,1,3,3]]))
print(out)
print(out.shape)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 11., 12.],
        [ 1.,  6., 15., 16.]])
torch.Size([3, 4])
tensor([[ 1.,  2.,  2.,  2.],
        [ 5.,  6.,  7.,  7.],
        [ 9., 10., 12., 12.]])
torch.Size([3, 4])


In [16]:
help(torch.linspace)

Help on built-in function linspace:

linspace(...)
    linspace(start, end, steps, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Creates a one-dimensional tensor of size :attr:`steps` whose values are evenly
    spaced from :attr:`start` to :attr:`end`, inclusive. That is, the value are:
    
    .. math::
        (\text{start},
        \text{start} + \frac{\text{end} - \text{start}}{\text{steps} - 1},
        \ldots,
        \text{start} + (\text{steps} - 2) * \frac{\text{end} - \text{start}}{\text{steps} - 1},
        \text{end})
    
    
    .. warning::
        Not providing a value for :attr:`steps` is deprecated. For backwards
        compatibility, not providing a value for :attr:`steps` will create a tensor
        with 100 elements. Note that this behavior is not reflected in the
        documented function signature and should not be relied on. In a future
        PyTorch release, failing to provide a value for :attr:`ste

In [14]:
# torch.index_select(input,dim,index,out=None)
d = torch.rand(4,4)
print(d)
index = torch.tensor([0,3,2])
print(index)
out = torch.index_select(d,dim=0,index=index)
# 按列取不同行
print(out)
print(out.shape)
out = torch.index_select(out,dim=1,index=torch.tensor([0,3]))
# 按列取不同行
print(out)
print(out.shape)

tensor([[0.7956, 0.9869, 0.5396, 0.1974],
        [0.6822, 0.7947, 0.4258, 0.3967],
        [0.6043, 0.5952, 0.3390, 0.4100],
        [0.6336, 0.7922, 0.3681, 0.3948]])
tensor([0, 3, 2])
tensor([[0.7956, 0.9869, 0.5396, 0.1974],
        [0.6336, 0.7922, 0.3681, 0.3948],
        [0.6043, 0.5952, 0.3390, 0.4100]])
torch.Size([3, 4])
tensor([[0.7956, 0.1974],
        [0.6336, 0.3948],
        [0.6043, 0.4100]])
torch.Size([3, 2])


In [19]:
# torch.masked_select(input,mask,out=None)
f = torch.linspace(1,16,16).view(4,4)
mask = torch.gt(f,9)
print(f)
print(mask)
out = torch.masked_select(f,mask)
print(out)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False,  True,  True,  True],
        [ True,  True,  True,  True]])
tensor([10., 11., 12., 13., 14., 15., 16.])


In [20]:
# torch.take(input,indices)
g = torch.linspace(1,16,16).view(4,4)
print(g)
h = torch.take(g,index = torch.tensor([0,15,13,10]))
print(h)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([ 1., 16., 14., 11.])


In [21]:
# torch.nonzero(input,out=None)
i = torch.tensor([[0,1,2,0],[2,3,0,1]])
out = torch.nonzero(i)
print(out)

tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 3]])


# 组合 拼接

- torch.cat(seq,dim=0,out=None):按照已经存在的维度进行拼接
- torch.stack(seq,dim=0,out=None):沿着一个新维度对输入张量序列进行连接。 序列中所有的张量都应该为相同形状。

In [26]:
j = torch.linspace(1,6,6).view(2,3)
k = torch.linspace(7,12,6).view(2,3)
print(j)
print(k)
out = torch.stack((j,k),dim=2)
print(out)
print(out.shape)
print(out[:,:,0])
print(out[:,:,1])

out = torch.stack((j,k),dim=1)
print(out)
print(out.shape)

out = torch.stack((j,k),dim=0)
print(out)
print(out.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[[ 1.,  7.],
         [ 2.,  8.],
         [ 3.,  9.]],

        [[ 4., 10.],
         [ 5., 11.],
         [ 6., 12.]]])
torch.Size([2, 3, 2])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])


In [28]:
out = torch.cat((j,k),dim=0)
print(out)
out = torch.cat((j,k),dim=1)
print(out)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])


# 填充

In [29]:
l = torch.full((2,3),3.33)
print(l)

tensor([[3.3300, 3.3300, 3.3300],
        [3.3300, 3.3300, 3.3300]])


# 切片

- torch.chunk(tensor,chunks,dim=0):按照某个维度平均分块（最后一个可能小于平均值）
- torch.split(tensor,split_size_or_sections,dim=0):按照某个维度依照第二个参数给出的list或者int进行分割tensor

In [41]:
m = torch.linspace(1,12,12).view(3,4)
print(m)
out = torch.chunk(m,2,dim=0)
print(out)
out = torch.chunk(m,2,dim=1)
print(out)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
(tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))
(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))


In [50]:
n = torch.linspace(1,12,12).view(3,4)
print(n)
out = torch.split(n,2,dim=0)
print(out)
out = torch.split(n,2,dim=1)
print(out)

out = torch.split(n,[1,2],dim=0)
print(out)
out = torch.split(n,[1,2,1],dim=1)
print(out)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
(tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))
(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))
(tensor([[1., 2., 3., 4.]]), tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]]))
(tensor([[1.],
        [5.],
        [9.]]), tensor([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.]]), tensor([[ 4.],
        [ 8.],
        [12.]]))


# 变形

-  torch.reshape(input,shape)
-  torch.t(input):只针对2D tensor转置
-  torch.transpose(input,dim0,dim1):交换两个维度
-  torch.squeeze(input,dim=None,out=None):去除那些维度大小为1的维度
-  torch.unbind(tensor,dim=0):去除某个维度
-  torch.unsqueeze(input,dim,out=None):在指定位置添加维度,dim=-1在最后添加
-  torch.flip(input,dims):按照给定维度翻转张量
-  torch.rot90(input,k,dims):按照指定维度和旋转次数进行张量旋转

In [51]:
o = torch.rand(2,3)
print(o)
out = torch.reshape(o,(3,2))
print(out)

tensor([[0.4176, 0.2336, 0.2591],
        [0.3411, 0.8867, 0.4005]])
tensor([[0.4176, 0.2336],
        [0.2591, 0.3411],
        [0.8867, 0.4005]])


In [52]:
p = torch.linspace(1,6,6).view(2,3)
print(p)
out = torch.t(p)
print(out)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [53]:
q = torch.rand(2,3,4)
print(q)
out = torch.transpose(q,1,2)
print(out)
out = torch.transpose(q,0,1)
print(out)

tensor([[[0.9888, 0.0155, 0.0528, 0.7863],
         [0.8869, 0.6600, 0.4699, 0.8965],
         [0.8320, 0.6582, 0.0845, 0.4513]],

        [[0.3956, 0.9352, 0.3403, 0.2406],
         [0.3031, 0.1658, 0.1991, 0.8396],
         [0.7089, 0.6804, 0.3560, 0.9971]]])
tensor([[[0.9888, 0.8869, 0.8320],
         [0.0155, 0.6600, 0.6582],
         [0.0528, 0.4699, 0.0845],
         [0.7863, 0.8965, 0.4513]],

        [[0.3956, 0.3031, 0.7089],
         [0.9352, 0.1658, 0.6804],
         [0.3403, 0.1991, 0.3560],
         [0.2406, 0.8396, 0.9971]]])
tensor([[[0.9888, 0.0155, 0.0528, 0.7863],
         [0.3956, 0.9352, 0.3403, 0.2406]],

        [[0.8869, 0.6600, 0.4699, 0.8965],
         [0.3031, 0.1658, 0.1991, 0.8396]],

        [[0.8320, 0.6582, 0.0845, 0.4513],
         [0.7089, 0.6804, 0.3560, 0.9971]]])


In [55]:
r = torch.rand(2,1,3)
print(r)
print(r.shape)
out = torch.squeeze(r)
print(out)
print(out.shape)

tensor([[[0.5352, 0.9923, 0.3547]],

        [[0.7620, 0.1928, 0.9086]]])
torch.Size([2, 1, 3])
tensor([[0.5352, 0.9923, 0.3547],
        [0.7620, 0.1928, 0.9086]])
torch.Size([2, 3])


In [58]:
s = torch.rand(2,2,3)
print(s)
print(s.shape)
out = torch.unbind(s,dim=0)
# print(out.shape)
print(out)
out = torch.unbind(s,dim=1)
# print(out.shape)
print(out)
out = torch.unbind(s,dim=2)
# print(out.shape)
print(out)

tensor([[[0.1767, 0.5190, 0.3751],
         [0.5347, 0.1648, 0.8326]],

        [[0.2329, 0.1216, 0.0524],
         [0.0655, 0.3150, 0.6624]]])
torch.Size([2, 2, 3])
(tensor([[0.1767, 0.5190, 0.3751],
        [0.5347, 0.1648, 0.8326]]), tensor([[0.2329, 0.1216, 0.0524],
        [0.0655, 0.3150, 0.6624]]))
(tensor([[0.1767, 0.5190, 0.3751],
        [0.2329, 0.1216, 0.0524]]), tensor([[0.5347, 0.1648, 0.8326],
        [0.0655, 0.3150, 0.6624]]))
(tensor([[0.1767, 0.5347],
        [0.2329, 0.0655]]), tensor([[0.5190, 0.1648],
        [0.1216, 0.3150]]), tensor([[0.3751, 0.8326],
        [0.0524, 0.6624]]))


In [59]:
t = torch.rand(2,3)
print(t.shape)
print(t)
out = torch.unsqueeze(t,dim=-1)
print(out.shape)
print(out)
out = torch.unsqueeze(t,dim=0)
print(out.shape)
print(out)
out = torch.unsqueeze(t,dim=1)
print(out.shape)
print(out)

torch.Size([2, 3])
tensor([[0.7018, 0.2643, 0.4915],
        [0.2416, 0.8697, 0.4686]])
torch.Size([2, 3, 1])
tensor([[[0.7018],
         [0.2643],
         [0.4915]],

        [[0.2416],
         [0.8697],
         [0.4686]]])
torch.Size([1, 2, 3])
tensor([[[0.7018, 0.2643, 0.4915],
         [0.2416, 0.8697, 0.4686]]])
torch.Size([2, 1, 3])
tensor([[[0.7018, 0.2643, 0.4915]],

        [[0.2416, 0.8697, 0.4686]]])


In [71]:
u = torch.rand(2,3)
print(u.shape)
print(u)
out = torch.flip(u,dims=[0,1])
print(out.shape)
print(out)
out = torch.flip(u,dims=[1,0])
print(out.shape)
print(out)

# 维度和旋转次数
out = torch.rot90(u, -1, dims=[0, 1]) #顺时针旋转90°  
print(out.shape)
print(out)


torch.Size([2, 3])
tensor([[0.9165, 0.4422, 0.3880],
        [0.4938, 0.5609, 0.2313]])
torch.Size([2, 3])
tensor([[0.2313, 0.5609, 0.4938],
        [0.3880, 0.4422, 0.9165]])
torch.Size([2, 3])
tensor([[0.2313, 0.5609, 0.4938],
        [0.3880, 0.4422, 0.9165]])
torch.Size([3, 2])
tensor([[0.4938, 0.9165],
        [0.5609, 0.4422],
        [0.2313, 0.3880]])
